config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#index"
    devise_for :users, controllers: {sessions: "users/sessions",
      registrations: "users/registrations", passwords: "users/passwords"}
    devise_scope :user do
      get "/signup", to: "users/registrations#new"
      post "/signup", to: "users/registrations#create"
      get "/login", to: "users/sessions#new"
      post "/login", to: "users/sessions#create"
      get "/logout", to: "users/sessions#destroy"
      get "/profile", to: "users#show"
      get "/profile/edit", to: "users#edit"
      get "/profile/change_password", to: "users/passwords#edit"
      get "/about", to: "users#about"
      get "/forgot_password", to: "users/passwords#new"
    end

    resources :users do
      resources :courses, only: :index
      resources :transactions, only: :index
    end

    resources :courses do
      resources :videos
    end

    resources :categories do
      member do
        get :courses, action: :show
      end
    end

    resources :searches, only: :index
    resources :transactions

    namespace :admin do
      resources :categories
      resources :courses
      resources :projects do
        member do
          get :members, to: "projects#members"
          get :images, to: "projects#images"
        end
      end
      resources :users
      resources :images
      resources :user_projects
      resources :locations
      resources :status_projects
    end
    get "/admin", to: "admin/admins#index"
    resources :images
    resources :locations
    resources :projects do
      member do
        get :images, to: "projects#images"
      end
    end
  end
end

app/models/location.rb
require 'csv'
class Location < ApplicationRecord
  belongs_to :image

  scope :filter_by_project, (lambda do |project_id|
    joins(:image)
    .where(images: {project_id: project_id})
  end)

  scope :filter_by_user, (lambda do |user|
    filter_by_project user.project_ids
  end)

  def self.to_csv
    attributes = %w{id project_id image_id x_min y_min x_max y_max text}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |location|
        csv << attributes.map{ |attr| location.send attr }
      end
    end
  end

  def coordinates
    coordinate.split(",").each(&:to_i)
  end

  def x_min
    coordinates[0]
  end

  def y_min
    coordinates[1]
  end

  def x_max
    coordinates[2]
  end

  def y_max
    coordinates[3]
  end

  def text
    content
  end

  def project_id
    image.project_id
  end
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < Admin::BasesController
  before_action :load_location

  def index
    case true
    when params[:image_id].present?
      image = Image.find_by id: params[:image_id]
      @locations = image.locations
      locations_info = locations_info @locations
      json_data = {"form": locations_info}
      @file_name = image.name
    when params[:project_id].present?
      @locations = Location.filter_by_project params[:project_id]
      json_data = {"project" => Array.new}
      Project.find_by(id: params[:project_id]).images.each do |image|
        json_data["project"] << {"form": locations_info(image.locations)}
      end
      @file_name = Project.find_by(id: params[:project_id]).name
    else
      @locations = Location.all
      json_data = {"system" => Array.new}
      Project.all.select(&:unlock_?).each do |project|
        hash = {"project" => Array.new}
        project.images.each do |image|
          hash["project"] << {"form": locations_info(image.locations)}
        end
        json_data["system"] << hash
      end
      @file_name = "System"
    end
    
    respond_to do |format|
      format.html
      format.json do
        send_data JSON.pretty_generate(json_data), filename: @file_name
      end
      format.csv do
        send_data @locations.to_csv, filename: @file_name
      end
    end
  end

  def edit
    coordinate = @location.coordinate
    coordinates = coordinate.split(",").map(&:to_i)
    @left = coordinates[0] > coordinates[2] ? coordinates[2] : coordinates[0]
    @top = coordinates[1] > coordinates[3] ? coordinates[1] : coordinates[3]
    # binding.pry
  end

  def update
    @location.update location_params
    # redirect_back fallback_location: root_path
  end

  private

  def location_params
    params.require(:location).permit %i(content)
  end

  def load_location
    @location = Location.find_by id: params[:id]
  end

  def locations_info locations
    locations.map do |l|
      {box: l.coordinate.split(",").map(&:to_i), text: l.content}
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :load_location

  def index
    case true
    when params[:image_id].present?
      image = Image.find_by id: params[:image_id]
      @locations = image.locations
      locations_info = locations_info @locations
      json_data = {"form": [locations_info]}
    when params[:project_id].present?
      @locations = Location.filter_by_project params[:project_id]
      json_data = {"project" => Array.new}
      Project.find_by(id: params[:project_id]).images.each do |image|
        json_data["project"] << {"form": locations_info(image.locations)}
      end
    else
      @locations = Location.all
      json_data = {"system" => Array.new}
      Project.all.select(&:unlock_?).each do |project|
        hash = {"project" => Array.new}
        project.images.each do |image|
          hash["project"] << {"form": locations_info(image.locations)}
        end
        json_data["system"] << hash
      end
    end

    respond_to do |format|
      format.html
      format.json do
        send_data JSON.pretty_generate(json_data), filename: "locations-data-#{Time.new.usec}.json"
      end
      format.csv do
        send_data @locations.to_csv, filename: "locations-data-#{Time.new.usec}.csv"
      end
    end
  end

  def new
    @location = Location.new image_id: params[:image_id], coordinate: params[:coordinate]
    coordinate = @location.coordinate
    coordinates = coordinate.split(",").map(&:to_i)
    @left = coordinates[0] > coordinates[2] ? coordinates[2] : coordinates[0]
    @top = coordinates[1] > coordinates[3] ? coordinates[1] : coordinates[3]
  end

  def create
    @location = Location.create image_id: params[:location][:image_id], coordinate: params[:location][:coordinate], content: params[:location][:content]
    redirect_back fallback_location: root_path
  end

  def edit; end

  def update
    @location.update location_params
    redirect_back fallback_location: root_path
  end

  private

  def location_params
    params.require(:location).permit %i(content)
  end

  def load_location
    @location = Location.find_by id: params[:id]
  end

  def locations_info locations
    locations.map do |l|
      {box: l.coordinate.split(",").map(&:to_i), text: l.content}
    end
  end
end

app/views/admin/locations/_edit_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="newModalLabel">Edit location</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <%= form_for [:admin, location], remote: true do |f| %>
        <div class="form-group">
          <%= f.label "Content", for: "content"%>
          <%= f.text_field :content, class: "form-control", id: "content" %>
        </div>
        <%= f.submit "Submit", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/locations/_form_edit.html.erb
<%= form_for [:admin, location], html: {class: "form-inline form-edit-location"}, remote: true do |f| %>
	<div class="form-group">
			<%= f.label "Content", for: "content", class: "sr-only" %>
			<%= f.text_field :content, class: "form-control", id: "content" %>
	</div>
	<%= f.button "", class: "btn btn-sm btn-primary" do %>
		<i class="mdi mdi-check mdi-9px"></i>
	<% end %>
<% end %>

app/views/admin/locations/_location.html.erb
<div class="location" id="location-id-<%= location.id %>">
  <ul class="">
    <li class="d-none coordinate"><%= location.coordinate %></li>
    <li class="content"><%= location.content %></li>
  </ul>
  <%= link_to edit_admin_location_path(location), class: "button-edit-location btn btn-sm btn-primary",
    id: "button-edit-#{location_counter + 1}", remote: true do %>
    <i class="mdi mdi-brush mdi-9px"></i>
  <% end %>
</div>

app/views/admin/locations/edit.js.erb
$('#edit-location').html(`
  <%= j render 'admin/locations/form_edit', location: @location %>
`);
$('#edit-location').css('top', '<%= @top %>px');
$('#edit-location').css('left', '<%= @left %>px');

app/views/admin/locations/update.js.erb
$('#edit-location').html('');
$('#location-id-<%= @location.id %> .content').html('<%= @location.content %>');