config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#index"
    devise_for :users, controllers: {sessions: "users/sessions",
      registrations: "users/registrations", passwords: "users/passwords"}
    devise_scope :user do
      get "/signup", to: "users/registrations#new"
      post "/signup", to: "users/registrations#create"
      get "/login", to: "users/sessions#new"
      post "/login", to: "users/sessions#create"
      get "/logout", to: "users/sessions#destroy"
      get "/profile", to: "users#show"
      get "/profile/edit", to: "users#edit"
      get "/profile/change_password", to: "users/passwords#edit"
      get "/about", to: "users#about"
      get "/forgot_password", to: "users/passwords#new"
    end

    resources :users do
      resources :courses, only: :index
      resources :transactions, only: :index
    end

    resources :courses do
      resources :videos
    end

    resources :categories do
      member do
        get :courses, action: :show
      end
    end

    resources :searches, only: :index
    resources :transactions

    namespace :admin do
      resources :categories
      resources :courses
      resources :projects do
        member do
          get :members, to: "projects#members"
          get :images, to: "projects#images"
        end
      end
      resources :users
      resources :images
      resources :user_projects
      resources :locations
      resources :status_projects
    end
    get "/admin", to: "admin/admins#index"
    resources :images
    resources :locations
    resources :projects do
      member do
        get :images, to: "projects#images"
      end
    end
  end
end

app/views/layouts/admin/_sidebar.html.erb
<!-- Sidebar -->
<div class="bg-light border-right" id="sidebar-wrapper">
  <div class="sidebar-heading">Start Bootstrap </div>
  <div class="list-group list-group-flush">
    <%= link_to "Manage Projects", admin_projects_path, class: "list-group-item list-group-item-action bg-light" %>
    <%= link_to "Manage Users", admin_users_path, class: "list-group-item list-group-item-action bg-light" %>
    <%= link_to "Manage Images", admin_images_path, class: "list-group-item list-group-item-action bg-light" %>
  </div>
</div>
<!-- /#sidebar-wrapper -->

app/views/layouts/admin/bases.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= render "layouts/rails_link" %>
    <meta name="turbolinks-cache-control" content="no-preview">
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="d-flex" id="wrapper">
      <%= render "layouts/admin/sidebar" %>
      <!-- Page Content -->
      <div id="page-content-wrapper">
        <nav class="d-flex navbar navbar-expand-lg navbar-light bg-light border-bottom">
          <button class="btn btn-primary" id="menu-toggle"><%= t ".toogle_menu" %></button>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <h3 class="flex-grow-1 text-center d-inline"><%= yield :Title %></h3>
        </nav>
        <div class="container-fluid">
          <%= yield %>
          <div id="modalImage" class="modalImage">
            <span class="close">&times;</span>
            <img class="modalImage-content" id="img01">
            <div id="caption"></div>
          </div>
        </div>
      </div>
      <!-- /#page-content-wrapper -->
    </div>
      <!-- /#wrapper -->
    <script>
      $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
      });
    </script>

  </body>
</html>