config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#index"
    devise_for :users, controllers: {sessions: "users/sessions",
      registrations: "users/registrations", passwords: "users/passwords"}
    devise_scope :user do
      get "/signup", to: "users/registrations#new"
      post "/signup", to: "users/registrations#create"
      get "/login", to: "users/sessions#new"
      post "/login", to: "users/sessions#create"
      get "/logout", to: "users/sessions#destroy"
      get "/profile", to: "users#show"
      get "/profile/edit", to: "users#edit"
      get "/profile/change_password", to: "users/passwords#edit"
      get "/about", to: "users#about"
      get "/forgot_password", to: "users/passwords#new"
    end

    resources :users do
      resources :courses, only: :index
      resources :transactions, only: :index
    end

    resources :courses do
      resources :videos
    end

    resources :categories do
      member do
        get :courses, action: :show
      end
    end

    resources :searches, only: :index
    resources :transactions

    namespace :admin do
      resources :categories
      resources :courses
      resources :projects do
        member do
          get :members, to: "projects#members"
          get :images, to: "projects#images"
        end
      end
      resources :users
      resources :images
      resources :user_projects
      resources :locations
      resources :status_projects
    end
    get "/admin", to: "admin/admins#index"
    resources :images
    resources :locations
    resources :projects do
      member do
        get :images, to: "projects#images"
      end
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  PROJECTS_PARAMS = %i(name avatar).freeze

  has_many :user_projects, dependent: :destroy
  has_many :users, through: :user_projects, source: :user
  has_many :images, dependent: :destroy
  has_one_attached :avatar

  enum status: {unlock_: 0, lock_: 1}

  validates :name, presence: true, length: {
      maximum: Settings.course.max_length_name,
      minimum: Settings.course.min_length_name
    }
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BasesController
  before_action :load_project, except: %i(new index create)

  def index
    @projects = Project.all
  end

  def show; end

  def new
    @project = Project.new
  end

  def edit; end

  def create
    @project = Project.new project_params
    @project.avatar.attach project_params[:avatar]
    if @project.save
      flash[:success] = "Create project successfully"
      redirect_to admin_projects_path
    else
      flash.now[:danger] = "Create project failed"
      render :new
    end
  end

  def update
    if @project.update project_params
      flash[:success] = "Update project successfully"
      redirect_to admin_projects_path
    else
      flash.now[:danger] = "Update project failed"
      render :edit
    end
  end

  def destroy
    if @project.destroy
      flash[:success] = "Update project successfully"
    else
      flash[:danger] = "Update project failed"
    end
    redirect_to admin_projects_path
  end

  def members
    @members = @project.users
  end

  def images
    @images = @project.images
  end

  private

  def project_params
    params.require(:project).permit Project::PROJECTS_PARAMS
  end

  def load_project
    @project = Project.find_by id: params[:id]
    return if @project

    flash[:danger] = t "not_permittion"
    redirect_to root_path
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :load_project, only: %i(show images)

  def index
    @projects = current_user.projects
  end

  def show; end

  def images
    @images = @project.images
  end

  private

  def load_project
    @project = Project.find_by id: params[:id]
  end
end

app/views/admin/projects/_download.html.erb
<% if project.status == "unlock_" %>
  <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
    aria-expanded="false" >
    Download data
    <i class="mdi mdi-database-export mdi-9px"></i>
  </button>
<% else %>
  <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
    aria-expanded="false" disabled="disabled" >
    Download data
    <i class="mdi mdi-database-export mdi-9px"></i>
  </button>
<% end %>
<div class="dropdown-menu">
  <%= link_to "CSV", "http://localhost:3000/en/admin/locations.csv?project_id=#{project.id}", class: "dropdown-item" %>
  <div class="dropdown-divider"></div>
  <%= link_to "JSON", "http://localhost:3000/en/admin/locations.json?project_id=#{project.id}", class: "dropdown-item" %>
</div>

app/views/admin/projects/_form.html.erb
<%= form_for [:admin, project] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group">
    <%= f.label "Avatar", for: "avatar" %>
    <%= f.file_field :avatar, class: "form-control", id: "avatar" %>
  </div>
  <div class="form-group">
    <%= f.label "Name", for: "name"%>
    <%= f.text_field :name, class: "form-control", id: "name", placeholder: "Enter project name" %>
  </div>
  <%= f.submit yield(:submit), class: "btn btn-primary" %>
<% end %>

app/views/admin/projects/_image.html.erb
<div class="responsive">
  <div class="gallery">
    <%= image_tag image.background, class: "myImg background-image", alt: image.name %>
    <div class="desc"><%= image.name %></div>
    <%= link_to "Preview", rails_blob_path(image.background, disposition: 'preview'), target: :blank %>
    |
    <%= link_to "Download", rails_blob_path(image.background, disposition: 'attachment'), target: :blank %>
    |
    <%= link_to "Detail", admin_image_path(image), target: :blank %>
    |
    <div class="d-inline btn-group-sm" id="image-download-<%= image.id %>">
      <%= render partial: "admin/images/download", locals: {image: image} %>
    </div>
  </div>
</div>

app/views/admin/projects/_list_projects.html.erb
<tr class="row">
  <th scope="row" class="col-md-1 table-project"><%= project_counter + 1 %></th>
  <td class="col-md-3 table-project"><%= image_tag project.avatar, class: "avatar-project-row" if project.avatar.attached? %></td>
  <td class="col-md-1 table-project"><%= project.name %></td>
  <td class="col-md-7 table-project">
    <%= link_to edit_admin_project_path(project), class: "btn btn-primary" do %>
      <i class="mdi mdi-brush mdi-9px"></i>
      Edit
    <% end %>
    <%= link_to admin_project_path(project), class: "btn btn-danger", method: :delete, data: {toggle: "tooltip", placement: :top, confirm: "Are you sure you?"} do %>
      <i class="mdi mdi-delete mdi-9px"></i>
      Delete
    <% end %>
    <%= link_to "Edit members", new_admin_user_project_path(object_id: project.id, type: :project), class: "btn btn-outline-success", remote: true %>
    <%= link_to admin_project_path(project), class: "btn btn-success" do %>
      Detail
      <i class="mdi mdi-forward mdi-9px"></i>
    <% end %>
    <span id=<%= "project-status-#{project.id}" %> >
      <%= render partial: "admin/projects/status", locals:{project: project} %>
    </span>
  </td>
</tr>

app/views/admin/projects/_member.html.erb
<tr>
  <th scope="row"><%= member_counter + 1 %></th>
  <td><%= member.name %></td>
  <td><%= member.email %></td>
  <td><%= member.role %></td>
  <td>
    <%= link_to admin_user_project_path(UserProject.find_by(user: member, project: @project)), method: :delete, data: {toggle: "tooltip", placement: :top, confirm: "Are you sure you?"}, class: "btn btn-danger" do %>
      Out project
      <i class="mdi mdi-forward mdi-9px"></i>
    <% end %>
  </td>
</tr>

app/views/admin/projects/_show_base.html.erb
<div class="w-100">
  <div class="row mt-5">
    <div class="col-1"></div>
    <div class="col-2">
      <%= image_tag project.avatar, class: "myImg avatar-project-row", id: "myImg" if project.avatar.attached? %>
    </div>
    <div class="col-4 detail-project-name">
      <%= link_to project.name, admin_project_path(project) %>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-1"></div>
    <div class="col-2">
      <%= link_to members_admin_project_path(project) do %>
        <%= project.users.size %> members
      <% end %>
    </div>
    <div class="col-2">
      <%= link_to images_admin_project_path(project) do %>
        <%= project.images.size %> images
      <% end %>
    </div>
    <div class="col-2" id=<%= "project-status-#{project.id}" %> >
      <%= render partial: "admin/projects/status", locals:{project: project} %>
    </div>
    <div class="col-2 btn-group" id=<%= "project-download-#{project.id}" %>>
      <%= render partial: "admin/projects/download", locals:{project: project} %>
    </div>
  </div>
</div>

app/views/admin/projects/_status.html.erb
<% if project.status == "unlock_" %>
  <%= link_to "Lock", admin_status_project_path(project, status: :lock_),
    method: :put, remote: true, class: "btn btn-danger" %>
<% else %>
  <%= link_to "Unlock", admin_status_project_path(project, status: :unlock_),
    method: :put, remote: true, class: "btn btn-warning" %>
<% end %>

app/views/admin/projects/_unlock.html.erb
<%= link_to "Lock", admin_status_project_path(project, status: :unlock),
  method: :put, remote: true, class: "btn btn-danger" %>

app/views/admin/projects/edit.html.erb
<%= provide :title, "Edit project" %>
<%= provide :submit, "Update" %>
<div class="container">
  <div class="row mt-5">
    <h2 class="w-100 text-center">Edit Project</h2>
  </div>
  <div class="row mb-5">
    <div class="col-2">
    </div>
    <div class="col-8">
      <%= render partial: "admin/projects/form", locals: {project: @project} %>
    </div>
    <div class="col-2">
    </div>
  </div>
</div>

app/views/admin/projects/images.html.erb
<%= render "admin/projects/show_base", project: @project %>
<div>
  <%= link_to "New images for project", new_admin_image_path(new_type: :multiple, project_id: @project.id), remote: :true, class: "btn btn-primary mt-5" %>
</div>
<div class="list-image w-100 mt-6" style="margin-top: 50px;">
  <%= render partial: "admin/projects/image", collection: @images, as: :image %>
  <div class="clearfix"></div>
</div>
<div class="modal fade" id="newModal" tabindex="-1" aria-labelledby="newModalLabel" aria-hidden="true"></div>

app/views/admin/projects/index.html.erb
<%= provide :title, "Manage projects" %>
<%= provide :Title, "Managa all projects" %>
<%= link_to "New project", new_admin_project_path, class: "btn btn-primary mt-5" %>
<div class="btn-group mt-5">
  <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Download all locations data
    <i class="mdi mdi-database-export mdi-9px"></i>
  </button>
  <div class="dropdown-menu">
    <%= link_to "CSV", "http://localhost:3000/en/admin/locations.csv", class: "dropdown-item" %>
    <div class="dropdown-divider"></div>
    <%= link_to "JSON", "http://localhost:3000/en/admin/locations.json", class: "dropdown-item" %>
  </div>
</div>
<table class="table table-hover mt-5">
  <thead>
    <tr class="row">
      <th scope="row" class="col-md-1 table-project">#</th>
      <th class="col-md-3 table-project">Avatar</th>
      <th class="col-md-3 table-project">Name</th>
      <th class="col-md-5 table-project">Action</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "admin/projects/list_projects", collection: @projects, as: :project %>
  </tbody>
</table>
<div class="modal fade" id="newModal" tabindex="-1" aria-labelledby="newModalLabel" aria-hidden="true"></div>

app/views/admin/projects/members.html.erb
<%= render "admin/projects/show_base", project: @project %>
<h2 class="text-center mt-5">
  Members of project
</h2>
<table class="table table-hover mt-5">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Role</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "admin/projects/member", collection: @members, as: :member %>
  </tbody>
</table>
<%# <div class="modal fade" id="newModal" tabindex="-1" aria-labelledby="newModalLabel" aria-hidden="true"></div> %>

app/views/admin/projects/new.html.erb
<%= provide :title, "Create project" %>
<%= provide :submit, "Create" %>
<div class="container">
  <div class="row mt-5">
    <h2 class="w-100 text-center">Create Project</h2>
  </div>
  <div class="row mb-5">
    <div class="col-2">
    </div>
    <div class="col-8">
      <%= render partial: "admin/projects/form", locals: {project: @project} %>
    </div>
    <div class="col-2">
    </div>
  </div>
</div>

app/views/admin/projects/show.html.erb
<%= render "admin/projects/show_base", project: @project %>